# Generated by Django 3.2.9 on 2021-11-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_entry_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.entry')),
            ],
        ),
    ]
